import JSZip from 'jszip';
import {
  generateAsciiBlock,
  generateTechStackMarkdown,
  generateSocialMarkdown,
  renderBlockSvg,
} from './svgGenerators';

const ASSET_DIR = './assets/readme-vibe';

function assetName(block, index) {
  return `${String(index + 1).padStart(2, '0')}-${block.type}.svg`;
}

export function exportReadme(profile, githubData) {
  const { blocks, style } = profile;
  const assets = [];
  const lines = [
    '<!-- Generated by readme.vibe — Profile Builder -->',
    '<div align="center">',
    '',
  ];

  blocks.forEach((block, i) => {
    const { type, config } = block;

    switch (type) {
      case 'text': {
        const align = config.align === 'left' ? '' : 'center';
        if (align) lines.push(`<div align="${align}">`);
        lines.push(config.content || '');
        if (align) lines.push('</div>');
        lines.push('');
        break;
      }
      case 'ascii':
        lines.push(generateAsciiBlock(config));
        lines.push('');
        break;
      case 'tech-stack':
        lines.push(generateTechStackMarkdown(config));
        lines.push('');
        break;
      case 'social-links':
        lines.push(generateSocialMarkdown(config));
        lines.push('');
        break;
      case 'pixel-avatar':
        if (config.sourceUrl) {
          lines.push(`<img src="${config.sourceUrl}" width="128" alt="avatar" style="image-rendering:pixelated;border:3px solid ${config.borderColor || style.accent};border-radius:8px"/>`);
        }
        lines.push('');
        break;
      case 'divider': {
        const char = config.style === 'line' ? '---' : config.style === 'stars' ? '✦ ✦ ✦' : '· · · · ·';
        lines.push(config.style === 'line' ? '---' : `<p>${char}</p>`);
        lines.push('');
        break;
      }
      default: {
        const svg = renderBlockSvg(block, githubData, style);
        if (svg) {
          const filename = assetName(block, i);
          assets.push({ filename, content: svg });
          lines.push(`<img src="${ASSET_DIR}/${filename}" alt="${type}" width="100%"/>`);
          lines.push('');
        }
        break;
      }
    }
  });

  lines.push('</div>');
  lines.push('');
  lines.push('<!-- readme.vibe -->');

  return {
    markdown: lines.join('\n'),
    assets,
    assetDir: ASSET_DIR,
  };
}

function triggerDownload(filename, blob) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.style.display = 'none';
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  // Revoke after the browser has picked up the blob URL
  window.setTimeout(() => URL.revokeObjectURL(url), 1500);
}

export function downloadFile(filename, content, mime = 'text/plain') {
  const blob = content instanceof Blob ? content : new Blob([content], { type: mime });
  triggerDownload(filename, blob);
}

export async function downloadAll(exportResult) {
  const zip = new JSZip();
  zip.file('README.md', exportResult.markdown);

  const assetsFolder = zip.folder('assets');
  const assetFolder = assetsFolder.folder('readme-vibe');
  exportResult.assets.forEach(({ filename, content }) => {
    assetFolder.file(filename, content);
  });

  const blob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });

  triggerDownload('readme-vibe-export.zip', blob);
  return { filename: 'readme-vibe-export.zip', assetCount: exportResult.assets.length };
}
