// README generators for each aesthetic theme

const langColors = {
  JavaScript: '#f7df1e', TypeScript: '#3178c6', Python: '#3572a5',
  Rust: '#dea584', Go: '#00add8', Java: '#b07219', 'C++': '#f34b7d',
  C: '#555555', Ruby: '#701516', Swift: '#fa7343', Kotlin: '#a97bff',
  PHP: '#4f5d95', CSS: '#563d7c', HTML: '#e34c26', Shell: '#89e051',
  Dart: '#00b4ab', Vue: '#41b883', Svelte: '#ff3e00', Elixir: '#6e4a7e',
};

function getLangColor(lang) {
  return langColors[lang] || '#888';
}

// ─── PIXEL / RETRO AESTHETIC ───────────────────────────────────────────────
export function generatePixelReadme(data) {
  const { username, name, bio, topLangs, topRepos, totalStars, followers, publicRepos, location } = data;

  const pixelDivider = `\`\`\`
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
\`\`\``;

  const langBadges = topLangs.map(l =>
    `![${l}](https://img.shields.io/badge/${encodeURIComponent(l)}-${getLangColor(l).replace('#','')}.svg?style=flat-square&logo=${l.toLowerCase().replace(/ /g,'+')}&logoColor=white)`
  ).join(' ');

  const repoCards = topRepos.slice(0, 4).map(r =>
    `[![${r.name}](https://github-readme-stats.vercel.app/api/pin/?username=${username}&repo=${r.name}&theme=dark&bg_color=0d0d0d&title_color=00ff41&icon_color=00ff41&border_color=00ff41&text_color=cccccc)](https://github.com/${username}/${r.name})`
  ).join('\n');

  return `<!-- PIXEL VIBES README — generated by readme.vibe -->
<div align="center">

\`\`\`
██████╗ ███████╗ █████╗ ██████╗ ███╗   ███╗███████╗
██╔══██╗██╔════╝██╔══██╗██╔══██╗████╗ ████║██╔════╝
██████╔╝█████╗  ███████║██║  ██║██╔████╔██║█████╗
██╔══██╗██╔══╝  ██╔══██║██║  ██║██║╚██╔╝██║██╔══╝
██║  ██║███████╗██║  ██║██████╔╝██║ ╚═╝ ██║███████╗
╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═════╝ ╚═╝     ╚═╝╚══════╝
\`\`\`

![Typing SVG](https://readme-typing-svg.demolab.com?font=Press+Start+2P&size=14&pause=1000&color=00FF41&center=true&width=600&lines=Hello%2C+I'm+${encodeURIComponent(name)}!;Level+${Math.floor(followers/10)+1}+Developer;${topLangs[0] || 'Code'}+Wizard+%F0%9F%A7%99;Insert+Coin+to+Continue...)

${pixelDivider}

### 👾 PLAYER ONE — ${name.toUpperCase()}

\`\`\`js
const ${username} = {
  name    : "${name}",
  class   : "Full-Stack Developer",${location ? `\n  location: "${location}",` : ''}${bio ? `\n  bio     : "${bio.replace(/"/g, "'")}",` : ''}
  xp      : ${totalStars} ⭐  |  ${publicRepos} repos  |  ${followers} followers,
  stack   : [${topLangs.map(l => `"${l}"`).join(', ')}],
  status  : "⚡ currently grinding side quests",
};
\`\`\`

${pixelDivider}

### 🏆 HIGH SCORES

<table align="center">
<tr>
<td>

![Stats](https://github-readme-stats.vercel.app/api?username=${username}&show_icons=true&theme=matrix&bg_color=0d0d0d&title_color=00ff41&icon_color=00ff41&border_color=00ff41&text_color=cccccc&hide_border=false)

</td>
<td>

![Streak](https://github-readme-streak-stats.herokuapp.com/?user=${username}&theme=matrix&background=0d0d0d&ring=00ff41&fire=00ff41&currStreakLabel=00ff41&border=00ff41)

</td>
</tr>
</table>

${pixelDivider}

### 🎮 EQUIPPED WEAPONS (TECH STACK)

${langBadges}

${pixelDivider}

### 📼 SAVED GAMES (TOP REPOS)

${repoCards}

${pixelDivider}

### 🕹️ CONTRIBUTION GRAPH — HACK THE PLANET

![Activity Graph](https://github-readme-activity-graph.vercel.app/graph?username=${username}&bg_color=0d0d0d&color=00ff41&line=00ff41&point=ffffff&area=true&hide_border=false&custom_title=CONTRIBUTION+GRAPH)

\`\`\`
INSERT COIN ▶  ▶  ▶  PRESS START TO COLLABORATE
\`\`\`

</div>`;
}

// ─── COTTAGE CORE / FLORAL AESTHETIC ──────────────────────────────────────
export function generateCottageReadme(data) {
  const { username, name, bio, topLangs, topRepos, totalStars, followers, publicRepos, location } = data;

  const flowerDivider = `<img src="https://raw.githubusercontent.com/andreasbm/readme/master/assets/lines/rainbow.png" width="100%">`;

  const badges = topLangs.map(l =>
    `![${l}](https://img.shields.io/badge/-${encodeURIComponent(l)}-${getLangColor(l).replace('#','')}.svg?style=for-the-badge&logo=${l.toLowerCase().replace(/ /g,'+')}&logoColor=white)`
  ).join(' ');

  return `<!-- 🌸 COTTAGE CORE README — generated by readme.vibe -->
<div align="center">

<!-- Header -->
<img src="https://capsule-render.vercel.app/api?type=waving&color=gradient&customColorList=12,14,16,18,20&height=200&section=header&text=${encodeURIComponent('✿ ' + name + ' ✿')}&fontColor=fff&fontSize=42&fontAlign=50&fontAlignY=38&desc=${encodeURIComponent(bio || 'growing code like wildflowers 🌿')}&descAlign=50&descAlignY=58&descSize=16" width="100%"/>

![Typing SVG](https://readme-typing-svg.demolab.com?font=Caveat&size=28&pause=1000&color=E75480&center=true&width=600&lines=welcome+to+my+garden+🌸;I+grow+${encodeURIComponent(topLangs[0] || 'code')}+with+care+🌱;every+commit+tells+a+story+📖;come+wander+through+my+repos+🍃)

${flowerDivider}

### 🌿 about me

> *"${bio || 'Code is poetry, and I\'m just here tending the garden.'}"*

\`\`\`
🌸  name     →  ${name}
🍃  craft    →  ${topLangs.slice(0,3).join(' · ') || 'developer'}${location ? `\n🌍  from     →  ${location}` : ''}
⭐  stars    →  ${totalStars} scattered across ${publicRepos} repos
🦋  friends  →  ${followers} lovely humans
\`\`\`

${flowerDivider}

### 🌺 my garden of languages

${badges}

<br/>

![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=${username}&layout=donut&theme=rose_pine&bg_color=fdf6f0&title_color=e75480&text_color=6b4c5b&border_color=f5c2c7&hide_border=false)

${flowerDivider}

### 🌻 blooming projects

${topRepos.slice(0, 4).map(r => `[![${r.name}](https://github-readme-stats.vercel.app/api/pin/?username=${username}&repo=${r.name}&theme=rose_pine&bg_color=fdf6f0&title_color=e75480&icon_color=e75480&border_color=f5c2c7&text_color=6b4c5b)](https://github.com/${username}/${r.name})`).join('\n')}

${flowerDivider}

### 🍀 growth rings

![Stats](https://github-readme-stats.vercel.app/api?username=${username}&show_icons=true&theme=rose_pine&bg_color=fdf6f0&title_color=e75480&icon_color=e75480&border_color=f5c2c7&text_color=6b4c5b&hide_border=false&include_all_commits=true&count_private=true)

![Activity](https://github-readme-activity-graph.vercel.app/graph?username=${username}&bg_color=fdf6f0&color=e75480&line=f5c2c7&point=e75480&area=true&hide_border=false&custom_title=contribution+garden+🌸)

<img src="https://capsule-render.vercel.app/api?type=waving&color=gradient&customColorList=12,14,16,18,20&height=120&section=footer" width="100%"/>

</div>

<!-- made with 🌸 by readme.vibe -->`;
}

// ─── DARK / HACKER / CYBERPUNK AESTHETIC ──────────────────────────────────
export function generateCyberpunkReadme(data) {
  const { username, name, bio, topLangs, topRepos, totalStars, followers, publicRepos, location } = data;

  const techBadges = topLangs.map(l =>
    `![${l}](https://img.shields.io/badge/${encodeURIComponent(l)}-${getLangColor(l).replace('#','')}.svg?style=flat-square&logo=${l.toLowerCase().replace(/ /g,'+')}&logoColor=white)`
  ).join(' ');

  return `<!-- ⚡ CYBERPUNK README — generated by readme.vibe -->
<div align="center">

<img src="https://capsule-render.vercel.app/api?type=cylinder&color=gradient&customColorList=0,2,20&height=180&section=header&text=${encodeURIComponent(name)}&fontColor=0ff&fontSize=50&fontAlign=50&fontAlignY=55&stroke=0ff&strokeWidth=2&desc=${encodeURIComponent('// ' + (bio || 'building the future, one commit at a time'))}&descAlign=50&descAlignY=75&descSize=14&descFontColor=ff0090" width="100%"/>

![Typing SVG](https://readme-typing-svg.demolab.com?font=Share+Tech+Mono&size=18&pause=800&color=00FFFF&background=00000000&center=true&width=700&lines=▸+SYSTEM+ONLINE+◂;▸+USER%3A+${encodeURIComponent(username.toUpperCase())}+◂;▸+STACK%3A+${encodeURIComponent(topLangs.slice(0,3).join(' · ').toUpperCase())}+◂;▸+STATUS%3A+HACKING+THE+MAINFRAME+◂)

---

\`\`\`bash
$ whoami
→  ${name}${location ? `  //  ${location}` : ''}

$ cat profile.json
{
  "handle"    : "@${username}",
  "bio"       : "${bio || 'code. coffee. repeat.'}",
  "languages" : [${topLangs.map(l => `"${l}"`).join(', ')}],
  "stars"     : ${totalStars},
  "repos"     : ${publicRepos},
  "followers" : ${followers},
  "status"    : "⚡ always building"
}

$ ls ~/projects/ --sort=stars
${topRepos.slice(0, 5).map(r => `→  ${r.name.padEnd(30)} [★${r.stargazers_count}]`).join('\n')}
\`\`\`

---

### ⟨ TECH MATRIX ⟩

${techBadges}

---

### ⟨ SYSTEM METRICS ⟩

<table>
<tr>
<td width="50%">

![Stats](https://github-readme-stats.vercel.app/api?username=${username}&show_icons=true&theme=radical&bg_color=0d0d1a&title_color=00ffff&icon_color=ff0090&border_color=00ffff&text_color=aaaacc)

</td>
<td width="50%">

![Streak](https://github-readme-streak-stats.herokuapp.com/?user=${username}&theme=radical&background=0d0d1a&ring=00ffff&fire=ff0090&currStreakLabel=00ffff&border=00ffff&sideLabels=aaaacc)

</td>
</tr>
</table>

---

### ⟨ TOP REPOS ⟩

${topRepos.slice(0, 4).map(r => `[![${r.name}](https://github-readme-stats.vercel.app/api/pin/?username=${username}&repo=${r.name}&theme=radical&bg_color=0d0d1a&title_color=00ffff&icon_color=ff0090&border_color=00ffff&text_color=aaaacc)](https://github.com/${username}/${r.name})`).join('\n')}

---

### ⟨ COMMIT GRID ⟩

![Activity](https://github-readme-activity-graph.vercel.app/graph?username=${username}&bg_color=0d0d1a&color=00ffff&line=ff0090&point=00ffff&area=true&hide_border=false&custom_title=COMMIT+FREQUENCY)

<img src="https://capsule-render.vercel.app/api?type=cylinder&color=gradient&customColorList=0,2,20&height=100&section=footer&reversal=true&stroke=0ff&strokeWidth=1" width="100%"/>

</div>

<!-- ⚡ generated by readme.vibe -->`;
}

// ─── MINIMAL / ELEGANT / EDITORIAL AESTHETIC ──────────────────────────────
export function generateMinimalReadme(data) {
  const { username, name, bio, topLangs, topRepos, totalStars, followers, publicRepos, location } = data;

  return `<!-- ◻ MINIMAL EDITORIAL README — generated by readme.vibe -->
<br/>

<div align="center">

# ${name}

*${bio || 'engineer · builder · thinker'}*

${location ? `📍 ${location}` : ''}

<br/>

[![GitHub followers](https://img.shields.io/github/followers/${username}?style=flat&color=111&labelColor=eee&label=followers)](https://github.com/${username})
![Repos](https://img.shields.io/badge/repos-${publicRepos}-111?style=flat&labelColor=eee)
![Stars](https://img.shields.io/badge/total%20stars-${totalStars}-111?style=flat&labelColor=eee)

</div>

---

### About

${bio ? `> ${bio}\n\n` : ''}I work with ${topLangs.slice(0, 3).join(', ')}${topLangs.length > 3 ? `, and ${topLangs.slice(3).join(', ')}` : ''}. I believe in writing clean, thoughtful code that solves real problems.

---

### Work

${topRepos.slice(0, 4).map(r => `**[${r.name}](https://github.com/${username}/${r.name})** — ${r.description || 'no description'} ${r.stargazers_count > 0 ? `· ★${r.stargazers_count}` : ''}`).join('\n\n')}

---

### Stack

${topLangs.map(l => `\`${l}\``).join(' · ')}

---

<div align="center">

![Stats](https://github-readme-stats.vercel.app/api?username=${username}&show_icons=true&hide_border=true&bg_color=ffffff&title_color=111&icon_color=111&text_color=555&hide_title=false)

</div>

---

<div align="center">
<sub>made with ◻ readme.vibe</sub>
</div>`;
}

// ─── Y2K / VAPORWAVE AESTHETIC ──────────────────────────────────────────
export function generateVaporwaveReadme(data) {
  const { username, name, bio, topLangs, topRepos, totalStars, followers, publicRepos, location } = data;

  const fullwidthName = name.split('').map(c => c === ' ' ? '　' : String.fromCharCode(c.charCodeAt(0) + (c.match(/[A-Za-z0-9]/) ? 0xFEE0 : 0))).join('');

  const badges = topLangs.map(l =>
    `![${l}](https://img.shields.io/badge/-${encodeURIComponent(l)}-${getLangColor(l).replace('#','')}.svg?style=for-the-badge&logo=${l.toLowerCase().replace(/ /g,'+')}&logoColor=white)`
  ).join(' ');

  return `<!-- ✦ VAPORWAVE README — generated by readme.vibe -->
<div align="center">

<img src="https://capsule-render.vercel.app/api?type=venom&color=gradient&customColorList=6,11,20&height=250&section=header&text=${encodeURIComponent('A E S T H E T I C')}&fontSize=40&fontColor=fff&fontAlign=50&fontAlignY=40&desc=${encodeURIComponent(name + ' ✦ ' + (bio || 'vibing through the digital ether'))}&descAlign=50&descAlignY=65&descSize=16&descFontColor=ffb3de" width="100%"/>

![Typing SVG](https://readme-typing-svg.demolab.com?font=VT323&size=30&pause=1000&color=FF71CE&background=00000000&center=true&width=700&lines=✦+${encodeURIComponent(name)}+✦;🌴+aesthetic+developer+🌴;💾+loading+vibes.exe...+💾;🌸+${encodeURIComponent(topLangs[0] || 'code')}+enjoyer+🌸)

<br/>

![Visitors](https://visitor-badge.laobi.icu/badge?page_id=${username}.${username}&right_color=pink)

---

### ✦ ｗｈｏ　ａｍ　ｉ ✦

\`\`\`
n a m e  ✦  ${name}${location ? `\nl o c    ✦  ${location}` : ''}
b i o    ✦  ${bio || 'vibing on the internet'}
s t a c k   ✦  ${topLangs.slice(0,4).join(' · ')}
s t a r s   ✦  ${totalStars} ⭐
r e p o s   ✦  ${publicRepos} 💾
\`\`\`

---

### 💾 ｔｅｃｈ　ｓｔａｃｋ

${badges}

---

### 🌴 ｓｔａｔｓ

<img src="https://github-readme-stats.vercel.app/api?username=${username}&show_icons=true&theme=synthwave&bg_color=1a0533&title_color=ff71ce&icon_color=01cdfe&border_color=b967ff&text_color=fffb96" width="49%"/>
<img src="https://github-readme-streak-stats.herokuapp.com/?user=${username}&theme=synthwave-dark&background=1a0533&ring=ff71ce&fire=01cdfe&currStreakLabel=ff71ce&border=b967ff" width="49%"/>

---

### 🌸 ｔｏｐ　ｐｒｏｊｅｃｔｓ

${topRepos.slice(0, 4).map(r =>
  `[![${r.name}](https://github-readme-stats.vercel.app/api/pin/?username=${username}&repo=${r.name}&theme=synthwave&bg_color=1a0533&title_color=ff71ce&icon_color=01cdfe&border_color=b967ff&text_color=fffb96)](https://github.com/${username}/${r.name})`
).join('\n')}

---

### 📼 ｃｏｎｔｒｉｂｕｔｉｏｎ　ｇｒｉｄ

![Activity](https://github-readme-activity-graph.vercel.app/graph?username=${username}&bg_color=1a0533&color=ff71ce&line=b967ff&point=01cdfe&area=true&hide_border=false&custom_title=✦+VIBES+✦)

<img src="https://capsule-render.vercel.app/api?type=venom&color=gradient&customColorList=6,11,20&height=120&section=footer&reversal=true" width="100%"/>

</div>

<!-- ✦ made with vaporwave energy by readme.vibe -->`;
}

// ─── AURORA / DREAMY PASTEL AESTHETIC ─────────────────────────────────────
export function generateAuroraReadme(data) {
  const { username, name, bio, topLangs, topRepos, totalStars, followers, publicRepos, location } = data;

  const badges = topLangs.map(l =>
    `![${l}](https://img.shields.io/badge/-${encodeURIComponent(l)}-${getLangColor(l).replace('#','')}.svg?style=flat-square&logo=${l.toLowerCase().replace(/ /g,'+')}&logoColor=white)`
  ).join(' ');

  return `<!-- 🌌 AURORA README — generated by readme.vibe -->
<div align="center">

<img src="https://capsule-render.vercel.app/api?type=soft&color=gradient&customColorList=0,1,2,3,4&height=200&section=header&text=${encodeURIComponent(name)}&fontColor=fff&fontSize=55&fontAlignY=50&animation=twinkling&desc=${encodeURIComponent(bio || 'dreaming in code ✨')}&descAlign=50&descAlignY=70&descSize=18&descFontColor=rgba(255,255,255,0.85)" width="100%"/>

![Typing SVG](https://readme-typing-svg.demolab.com?font=Quicksand&size=22&weight=600&pause=1000&color=A78BFA&background=00000000&center=true&width=600&lines=hey+there!+i'm+${encodeURIComponent(name)}+✨;dreaming+in+${encodeURIComponent(topLangs[0] || 'code')}+🌙;${publicRepos}+repos%2C+${totalStars}+stars+⭐;always+building+something+magical+🔮)

---

### 🌙 about me

${bio ? `> ✨ *${bio}*` : ''}

| | |
|---|---|
| 🌍 | ${location || 'somewhere on this planet'} |
| 💻 | ${topLangs.slice(0,3).join(', ')} |
| ⭐ | ${totalStars} stars across ${publicRepos} repos |
| 🤝 | ${followers} followers |

---

### 🔮 spells i cast (languages)

${badges}

---

### 🌠 github constellation

<a href="https://github.com/${username}">
  <img src="https://github-readme-stats.vercel.app/api?username=${username}&show_icons=true&theme=tokyonight&bg_color=0d1117&title_color=a78bfa&icon_color=38bdf8&border_color=7c3aed&text_color=c4b5fd&border_radius=12" width="49%"/>
  <img src="https://github-readme-streak-stats.herokuapp.com/?user=${username}&theme=tokyonight&background=0d1117&ring=a78bfa&fire=f472b6&currStreakLabel=a78bfa&border=7c3aed" width="49%"/>
</a>

---

### 🌌 projects that light up the sky

${topRepos.slice(0, 4).map(r =>
  `[![${r.name}](https://github-readme-stats.vercel.app/api/pin/?username=${username}&repo=${r.name}&theme=tokyonight&bg_color=0d1117&title_color=a78bfa&icon_color=38bdf8&border_color=7c3aed&text_color=c4b5fd&border_radius=12)](https://github.com/${username}/${r.name})`
).join('\n')}

---

### 🌊 the tide of commits

![Activity](https://github-readme-activity-graph.vercel.app/graph?username=${username}&bg_color=0d1117&color=a78bfa&line=7c3aed&point=f472b6&area=true&hide_border=false&custom_title=✨+aurora+commit+graph)

<img src="https://capsule-render.vercel.app/api?type=soft&color=gradient&customColorList=0,1,2,3,4&height=120&section=footer&animation=twinkling" width="100%"/>

</div>

<!-- 🌌 made with starlight by readme.vibe -->`;
}

// ─── BRUTALIST / BOLD TYPOGRAPHIC AESTHETIC ───────────────────────────────
export function generateBrutalistReadme(data) {
  const { username, name, bio, topLangs, topRepos, totalStars, followers, publicRepos, location } = data;

  return `<!-- ■ BRUTALIST README — generated by readme.vibe -->

# ${name.toUpperCase()}.

**${bio || 'I build things on the internet.'}**

---

## I USE:

${topLangs.map(l => `### ${l.toUpperCase()}`).join('\n')}

---

## NUMBERS:

| REPOS | STARS | FOLLOWERS |
|:---:|:---:|:---:|
| **${publicRepos}** | **${totalStars}** | **${followers}** |

---

## WORK:

${topRepos.slice(0, 5).map((r, i) => `**${i + 1}. [${r.name.toUpperCase()}](https://github.com/${username}/${r.name})** — ${r.description || 'no description.'} ★${r.stargazers_count}`).join('\n\n')}

---

## STATS:

![Stats](https://github-readme-stats.vercel.app/api?username=${username}&show_icons=false&hide_border=true&bg_color=FFFFFF&title_color=000000&text_color=000000&hide_rank=false)

---

## ACTIVITY:

![Activity](https://github-readme-activity-graph.vercel.app/graph?username=${username}&bg_color=FFFFFF&color=000000&line=000000&point=000000&area=false&hide_border=true&custom_title=COMMITS)

---

*→ [github.com/${username}](https://github.com/${username})*${location ? `\n*→ based in ${location}*` : ''}

---

<sub>■ README.VIBE</sub>`;
}

// ─── GALAXY / SPACE AESTHETIC ─────────────────────────────────────────────
export function generateGalaxyReadme(data) {
  const { username, name, bio, topLangs, topRepos, totalStars, followers, publicRepos, location } = data;

  const badges = topLangs.map(l =>
    `![${l}](https://img.shields.io/badge/-${encodeURIComponent(l)}-${getLangColor(l).replace('#','')}.svg?style=flat-square&logo=${l.toLowerCase().replace(/ /g,'+')}&logoColor=white)`
  ).join(' ');

  return `<!-- 🚀 GALAXY README — generated by readme.vibe -->
<div align="center">

<img src="https://capsule-render.vercel.app/api?type=rect&color=gradient&customColorList=0,2,4,12&height=220&section=header&text=⚡ ${encodeURIComponent(name)} ⚡&fontColor=ffffff&fontSize=45&fontAlign=50&fontAlignY=55&desc=${encodeURIComponent('// ' + (bio || 'navigating the digital cosmos'))}&descAlign=50&descAlignY=75&descSize=15&descFontColor=88aaff" width="100%"/>

![Typing SVG](https://readme-typing-svg.demolab.com?font=Orbitron&size=16&pause=1000&color=6699FF&background=00000000&center=true&width=700&lines=🚀+MISSION+CONTROL+ONLINE;🌌+EXPLORING+${encodeURIComponent(topLangs.slice(0,2).join('+%2F+').toUpperCase())};⭐+${totalStars}+STARS+COLLECTED;📡+SIGNAL+STRONG)

---

### 🌌 MISSION BRIEFING

\`\`\`yaml
ASTRONAUT : ${name}
SECTOR    : ${location || 'Unknown Quadrant'}
BIO       : ${bio || 'Lost in the source code nebula'}
LANGUAGES : [${topLangs.join(', ')}]
STARS     : ${totalStars} ⭐
MISSIONS  : ${publicRepos} repositories
ALLIES    : ${followers} collaborators
\`\`\`

---

### 🛸 TECH ARSENAL

${badges}

---

### 📡 TELEMETRY

<img src="https://github-readme-stats.vercel.app/api?username=${username}&show_icons=true&theme=nightowl&bg_color=0c0f1a&title_color=6699ff&icon_color=88bbff&border_color=334477&text_color=aabbdd" width="49%"/>
<img src="https://github-readme-streak-stats.herokuapp.com/?user=${username}&theme=nightowl&background=0c0f1a&ring=6699ff&fire=88bbff&currStreakLabel=6699ff&border=334477&sideLabels=aabbdd" width="49%"/>

---

### 🌠 NOTABLE MISSIONS

${topRepos.slice(0, 4).map(r =>
  `[![${r.name}](https://github-readme-stats.vercel.app/api/pin/?username=${username}&repo=${r.name}&theme=nightowl&bg_color=0c0f1a&title_color=6699ff&icon_color=88bbff&border_color=334477&text_color=aabbdd)](https://github.com/${username}/${r.name})`
).join('\n')}

---

### 🌌 ORBITAL ACTIVITY

![Activity](https://github-readme-activity-graph.vercel.app/graph?username=${username}&bg_color=0c0f1a&color=6699ff&line=334477&point=88bbff&area=true&hide_border=false&custom_title=🚀+ORBITAL+COMMIT+TRAJECTORY)

<img src="https://capsule-render.vercel.app/api?type=rect&color=gradient&customColorList=0,2,4,12&height=80&section=footer&reversal=true" width="100%"/>

</div>

<!-- 🚀 charted by readme.vibe -->`;
}

export const THEMES = [
  {
    id: 'pixel',
    name: 'Pixel / Retro',
    emoji: '👾',
    desc: 'Terminal green on black. ASCII art headers, monospace everything.',
    colors: ['#00ff41', '#0d1a0d', '#00cc33'],
    tags: ['dark', 'retro', 'gamer'],
    // Card visual identity
    card: {
      bg: 'linear-gradient(145deg, #060d06 0%, #0a180a 100%)',
      accent: '#00ff41',
      textColor: '#00ff41',
      fontStyle: 'mono',
      previewLines: ['> whoami', '// hacker.exe', '▓▓▓ LOADING ▓▓▓'],
      borderStyle: '1px solid #00ff4130',
      glowColor: '#00ff4120',
    },
    generate: generatePixelReadme,
  },
  {
    id: 'cottage',
    name: 'Cottage Core',
    emoji: '🌸',
    desc: 'Soft warm pinks, floral dividers, a cozy handwritten feel.',
    colors: ['#e8607a', '#fff0f3', '#f9c4cf'],
    tags: ['soft', 'cute', 'warm'],
    card: {
      bg: 'linear-gradient(145deg, #2a0d14 0%, #1e0a10 100%)',
      accent: '#f9a8bb',
      textColor: '#fce4ec',
      fontStyle: 'serif',
      previewLines: ['✿ about me', '🌿 growing ideas', '🍃 one commit at a time'],
      borderStyle: '1px solid #f9a8bb28',
      glowColor: '#e8607a22',
    },
    generate: generateCottageReadme,
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    emoji: '⚡',
    desc: 'Neon cyan slices through hot pink on pure black.',
    colors: ['#00f5ff', '#ff0090', '#0d0d1a'],
    tags: ['dark', 'neon', 'edgy'],
    card: {
      bg: 'linear-gradient(145deg, #050516 0%, #0a0a22 100%)',
      accent: '#00f5ff',
      textColor: '#e0f7ff',
      fontStyle: 'mono',
      previewLines: ['⟨ SYSTEM ONLINE ⟩', '$ status: hacking', '// neon://ready'],
      borderStyle: '1px solid #00f5ff25',
      glowColor: '#00f5ff1a',
    },
    generate: generateCyberpunkReadme,
  },
  {
    id: 'minimal',
    name: 'Editorial',
    emoji: '◻',
    desc: 'Stark type on white. No noise, just structure and precision.',
    colors: ['#0f0f0f', '#f5f5f5', '#888888'],
    tags: ['clean', 'minimal', 'pro'],
    card: {
      bg: 'linear-gradient(145deg, #f9f9f9 0%, #efefef 100%)',
      accent: '#111',
      textColor: '#111',
      fontStyle: 'sans',
      previewLines: ['# Name.', '— bio goes here', 'Work · Stack · Stats'],
      borderStyle: '1px solid #11111115',
      glowColor: '#11111108',
      dark: true, // renders dark text on light bg
    },
    generate: generateMinimalReadme,
  },
  {
    id: 'vaporwave',
    name: 'Vaporwave',
    emoji: '🌴',
    desc: 'Full-width A E S T H E T I C. Purple, pink, cyan, nostalgia.',
    colors: ['#ff71ce', '#b967ff', '#01cdfe'],
    tags: ['y2k', 'aesthetic', 'colourful'],
    card: {
      bg: 'linear-gradient(145deg, #1a0533 0%, #0d0020 100%)',
      accent: '#ff71ce',
      textColor: '#ffb3de',
      fontStyle: 'display',
      previewLines: ['Ａ Ｅ Ｓ Ｔ Ｈ Ｅ Ｔ Ｉ Ｃ', '✦ vibing ✦', '💾 loading...'],
      borderStyle: '1px solid #b967ff30',
      glowColor: '#b967ff1e',
    },
    generate: generateVaporwaveReadme,
  },
  {
    id: 'aurora',
    name: 'Aurora',
    emoji: '🌌',
    desc: 'Dreamy violet-to-teal gradients, soft glow, starfield depth.',
    colors: ['#a78bfa', '#34d399', '#f472b6'],
    tags: ['dark', 'dreamy', 'gradient'],
    card: {
      bg: 'linear-gradient(145deg, #0d0d22 0%, #0a1020 50%, #080d18 100%)',
      accent: '#a78bfa',
      textColor: '#d8b4fe',
      fontStyle: 'sans',
      previewLines: ['✨ hey, I\'m dreaming', '🌙 in code', '🔮 building magic'],
      borderStyle: '1px solid #a78bfa22',
      glowColor: '#a78bfa18',
    },
    generate: generateAuroraReadme,
  },
  {
    id: 'brutalist',
    name: 'Brutalist',
    emoji: '■',
    desc: 'Heavy type. No decorations. Raw, direct, unforgettable.',
    colors: ['#ff3300', '#f0f0f0', '#0a0a0a'],
    tags: ['bold', 'editorial', 'type'],
    card: {
      bg: 'linear-gradient(145deg, #0a0a0a 0%, #111 100%)',
      accent: '#ff3300',
      textColor: '#f0f0f0',
      fontStyle: 'heavy',
      previewLines: ['NAME.', 'I BUILD THINGS.', '— NO FRILLS —'],
      borderStyle: '1px solid #ff330025',
      glowColor: '#ff330018',
    },
    generate: generateBrutalistReadme,
  },
  {
    id: 'galaxy',
    name: 'Galaxy',
    emoji: '🚀',
    desc: 'Deep space navy, orbital stats, sci-fi mission briefing.',
    colors: ['#4d9fff', '#0c0f1a', '#7ec8ff'],
    tags: ['dark', 'space', 'sci-fi'],
    card: {
      bg: 'linear-gradient(145deg, #050810 0%, #080c1a 50%, #060a16 100%)',
      accent: '#4d9fff',
      textColor: '#a8c8ff',
      fontStyle: 'mono',
      previewLines: ['🚀 MISSION CONTROL', 'ASTRONAUT: ready', '📡 signal: strong'],
      borderStyle: '1px solid #4d9fff20',
      glowColor: '#4d9fff18',
    },
    generate: generateGalaxyReadme,
  },
];
